# Generated by Django 5.1.7 on 2025-04-02 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('manager', 'Manager'), ('executive', 'Executive')], max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='preferred_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='remote_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='portfolio_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('phone', 'Phone')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker')),
            ],
            options={
                'unique_together': {('job', 'jobseeker')},
            },
        ),
    ]
