# Generated by Django 5.1.7 on 2025-04-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobalert_jobseeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
    ]
