# Generated by Django 5.1.7 on 2025-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobseeker_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
