# Generated by Django 5.1.7 on 2025-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_benefit_jobcategory_skill_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['industry'], name='jobs_jobpos_industr_48f129_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['experience_level'], name='jobs_jobpos_experie_e4bfc2_idx'),
        ),
    ]
